# Generated by Django 2.1.5 on 2019-02-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain'),
        ),
        migrations.AlterField(
            model_name='email',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Domain'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
