# Generated by Django 2.1.5 on 2019-02-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20190222_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alias',
            table='virtual_aliases',
        ),
        migrations.AlterModelTable(
            name='domain',
            table='virtual_domains',
        ),
        migrations.AlterModelTable(
            name='email',
            table='virtual_users',
        ),
    ]
